// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
  ext.kotlin_version = '1.7.22'
  repositories {
    mavenCentral()
    maven {
      url "https://releases.jfrog.io/artifactory/oss-releases"
    }

    gradlePluginPortal()
    google()
    jcenter()
  }


  // https://mvnrepository.com/artifact/org.jfrog.buildinfo/build-info-extractor
  //implementation 'org.jfrog.buildinfo:build-info-extractor:2.11.3'
// https://mvnrepository.com/artifact/org.jfrog.buildinfo/build-info-extractor
//  implementation group: 'org.jfrog.buildinfo', name: 'build-info-extractor', version: '2.11.3'


  dependencies {
    classpath 'com.android.tools.build:gradle:4.2.2'
    classpath 'com.google.protobuf:protobuf-gradle-plugin:0.8.8'
    classpath "org.jfrog.buildinfo:build-info-extractor-gradle:4.7.5"
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

    // NOTE: Do not place your application dependencies here; they belong
    // in the individual module build.gradle files
  }
}

ext {
  versions = [compileSdk        : 28,
              targetSdk         : 28,
              minSdk            : 19,
              buildTools        : "28.0.3",
              androidSupport    : "28.0.0", 
              androidSupportTest: '0.5']

  snapshot = !Project.hasProperty("snapshot") || Boolean.parseBoolean(Project.property("snapshot"))
}

allprojects {

  repositories {
    mavenCentral()
    google()
    jcenter()
    gradlePluginPortal()
    maven { url 'https://jitpack.io' }
  }

  configurations.all {
    resolutionStrategy.cacheChangingModulesFor 5, 'seconds'
  }
}

tasks.withType(JavaCompile) {
  options.encoding = "UTF-8"
}

task clean(type: Delete) {
  delete rootProject.buildDir
}

